repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types_or: [rust, toml]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --workspace -- -D warnings
        language: system
        types_or: [rust, toml]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: cargo test --workspace
        language: system
        types_or: [rust, toml]
        pass_filenames: false
